### PR TITLE
DO NOT MERGE: initial work on handle_reservation

### PR DESCRIPTION
**Pull request by srabraham**
@mikeburg : I started on https://github.com/burningmantech/ranger-clubhouse-web/issues/667 today. Mostly I've been having to learn a lot of Laravel/Eloquent (amd PHP) stuff, so it's been a slow start

I have two questions for you at this point:
1. do you have any idea why `php artisan make:migration create_handle_reservation_table` isn't creating a more comprehensive migration for me? It's my understanding that it should read through the `fillable` and other properties to make a richer migration. It's fine if I need to write the migration myself; I'm just confused because I thought it's supposed to do this for me
2. could you please do an initial pass on on the model file and let me know what needs changing?

### CODE REVIEW

**Comment by mikeburg** [comment]
@srabraham I haven't seen any reference to the make:migration command using the $fillable column on a Eloquent model to create a schema. Can you point me to the framework document describing this behavior? That's a pretty cool feature if that's actually there.

The model file looks fine for a first pass.

**Comment by srabraham** [comment]
> @srabraham I haven't seen any reference to the make:migration command using the $fillable column on a Eloquent model to create a schema. Can you point me to the framework document describing this behavior? That's a pretty cool feature if that's actually there.
> 
> The model file looks fine for a first pass.

Sigh...yeah, I guess that's not a feature. I must've misread something. There's certainly a steep learning curve to Laravel, as reflected in small part by the many many `php artisan` commands available.
Maybe I should ask at this point before doing the bulk of the PHP work: it seems like for this HandleReservation table and endpoint, I want a model, a controller, maybe a policy, and maybe a factory. Is there any piece to that that I'm missing or that I don't actually need?
I want to fully focus on the API part of this before doing much on the -web side. I need that as a digestable bit of work.

**Comment by mikeburg** [comment]
> Sigh...yeah, I guess that's not a feature. I must've misread something. There's certainly a steep learning curve to Laravel, as reflected in small part by the many many `php artisan` commands available. Maybe I should ask at this point before doing the bulk of the PHP work: it seems like for this HandleReservation table and endpoint, I want a model, a controller, maybe a policy, and maybe a factory. Is there any piece to that that I'm missing or that I don't actually need? I want to fully focus on the API part of this before doing much on the -web side. I need that as a digestable bit of work.

You have the all the pieces. The factory, in the context of testing, is very straight forward. 

Save yourself some learning pain by copy-n-pasting the other controller & models. The Award or Swag model & controllers might be a good starting point. Both are fairly straightforward, simple CRUD controllers & models.

**Comment by srabraham** [comment]
> > Sigh...yeah, I guess that's not a feature. I must've misread something. There's certainly a steep learning curve to Laravel, as reflected in small part by the many many `php artisan` commands available. Maybe I should ask at this point before doing the bulk of the PHP work: it seems like for this HandleReservation table and endpoint, I want a model, a controller, maybe a policy, and maybe a factory. Is there any piece to that that I'm missing or that I don't actually need? I want to fully focus on the API part of this before doing much on the -web side. I need that as a digestable bit of work.
> 
> You have the all the pieces. The factory, in the context of testing, is very straight forward.
> 
> Save yourself some learning pain by copy-n-pasting the other controller & models. The Award or Swag model & controllers might be a good starting point. Both are fairly straightforward, simple CRUD controllers & models.

actually this is all feeling a lot simpler now. It didn't take too much longer today for me to get the migration, model, controller, and route all functional (testing the APIs via cURL). I still have to get the policy in place, then I'll probably send you a proper initial PR

**Pull request closed without merging**
