### PR TITLE
Dockerize

### LINKED ISSUE #1: Dockerize the Clubhouse API service
Clubhouse API service needs to be Dockerized for deployment.

### PR DESCRIPTION
**Pull request by wsanchez**
Fixes #1

Requirements:

- [x] [Base PHP + web server container](https://hub.docker.com/r/burningman/php-nginx/)
- [x] Composer - build artifacts
- [x] Artisan mumble mumble
- [x] Nginx configuration
- [x] Test script

### CODE REVIEW

**Comment by wsanchez** [comment]
@mikeburg Don't merge me, yo.  (I wasn't done with #3)

**Comment by mikeburg** [comment]
yo @wsanchez, copy that.

**Comment by wsanchez** [comment]
@mikeburg I think I have most of this wired up but am having trouble (as I always do) with the PHP-specific bits of the web server config.

If you try this out (`./bin/build && ./bin/run`), and hit http://localhost:8000/api/index.php, then you should see this error in the logs:

```console
2018/12/17 20:32:08 [notice] 11#11: *1 "^/api/(.*)$" matches "/api/index.php", client: 172.17.0.1, server: , request: "GET /api/index.php HTTP/1.1", host: "localhost:8000"
2018/12/17 20:32:08 [error] 11#11: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.17.0.1, server: , request: "GET /api/index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "localhost:8000"
```

This general means `SCRIPT_FILENAME` is wrong.  I've tried my own version of the config and got different results, so what I've checked in tries to match your config above as well as I could.

**Comment by wsanchez** [comment]
@mikeburg Did you mean to push ffaf765 to this branch?  (Not that I mind, but it seems unrelated.)

**Comment by mikeburg** [comment]
@wsanchez http://localhost:8000/api/index.php is not a valid URL, so yah things are going to barf. HOWEVER, http://localhost:8000/api/config is a valid URL and does WORK. Congratulations! 

I tweaked the Dockerfile and nginx scripts a little:

-  ./storage is created when building the Docker image since Laravel wants a place to store logs and cache files. 
- The http errors to error page rewrite has been removed. The framework will generate 400 and 404 errors with an information payload that needs to be passed as-is back up the frontend.
- Added support for CORS.

There's still some work that needs to be done wrt setting up the environment variables. I was able to test by copying .env.clubhouse into the live Docker image's .env file, run 'php artisan cache:config' to pick up the new configuration and have things works.

**Comment by wsanchez** [comment]
@mikeburg That's great!

I'm not seeing your changes, but I do see a CORS-related commit on this branch; perhaps you committed the wrong thing?

Do you have any suggestions for tests I can run to check that the server is happy?  I can start with checking that the config URL gives me back a valid document, if that's good enough.

**Pull request merged**
