### PR TITLE
Add support for DB Migration prior to launch

### LINKED ISSUE #11: Figure out when to deal with pending database migrations.
Laravel, the web framework used for the backend, supports database migrations. When the backend is being deployed, the outstanding migrations should be executed.

The command to do this is `php artisan migrate`. 

Migration errors should stop the build task, and report the problems.  A migration can be rolled back by the command `php artisan migrate:rollback'

See the laravel documentation for more information:
https://laravel.com/docs/5.7/migrations

### LINKED ISSUE #21: Migration failed: Syntax error or access violation: 1071 Specified key was too long
In PR #18, I am seeing an error while migrating from an empty database in the [Travis logs](https://travis-ci.com/burningmantech/ranger-clubhouse-api/jobs/180421862):

```console
Migrating: 2019_01_01_102126_create_action_logs_table
[2019-02-25 13:55:09] production.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `action_logs` add index `action_logs_person_id_event_created_at_index`(`person_id`, `event`, `created_at`)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `action_logs` add index `action_logs_person_id_event_created_at_index`(`person_id`, `event`, `created_at`)) at /var/www/application/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes at /var/www/application/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458)
```

...

```console
In Connection.php line 664:
                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t  
  oo long; max key length is 767 bytes (SQL: alter table `action_logs` add in  
  dex `action_logs_person_id_event_created_at_index`(`person_id`, `event`, `c  
  reated_at`))                                                                 
                                                                               
In Connection.php line 458:
                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t  
  oo long; max key length is 767 bytes                                         
```

### PR DESCRIPTION
**Pull request by wsanchez**
Fixes #11 
Fixes #21

### CODE REVIEW

**Comment by wsanchez** [comment]
This also adds an `env` subcommand to `aws_update` which let you get the process environment for the service.  It also lets you changed the environment and re-deploy.

**Comment by wsanchez** [comment]
OK… CI is failing because it's trying to migrate and we don't have a database in CI.

**Comment by wsanchez** [comment]
OMG OK we have DB connectivity!

**Comment by wsanchez** [comment]
Argh this deployed, which is no bueno for a PRB.

**Comment by wsanchez** [comment]
OK rolled back.  The good news is that it deployed, attempted a migration, and errored out, which was expected due to manual schema changes earlier.

**Comment by wsanchez** [comment]
So I think this will do what it should when we merge, but we need to plan to deal with the schema mismatch.

@mikeburg I think step one should be to clone production to staging, which I don't think we've done for a while.  I can do that on blaster.  I think this is key so that we're trial running on staging as we would on prod.  Yes?

Next step is something about the mismatch so that when this PR deploys, it will not start the server (which it won't do if migrate fails).

**Comment by wsanchez** [comment]
FYI in the end I decided not to use the MySQL service provided by Travis CI because it is MySQL 5.7 and we're still on 5.6 in production; we should be testing with the same version.

The solution, then, was to start a DB container with MySQL 5.6, and link to it when starting the app container.  That gets you a network connection to MySQL in a way Docker supports, so the networking pain I spent a week debugging didn't end up being needed.  Meh.  `test_docker` now has the two-container thing working.

Another big plus to that is that I can run `test_docker` on my laptop and test the same thing, so less stuff to debug in the Travis environment.

**Comment by mikeburg** [comment]
@wsanchez I agree - go ahead and clone the production database to staging.

**Comment by wsanchez** [comment]
@mikeburg Copy that; cloning.  Hopefully we'll have staging dialed in tomorrow, then I'll switch to the Ember app, which should be a lot simpler.

**Comment by wsanchez** [comment]
Clone completed.

**Comment by wsanchez** [comment]
Well for some reason I'm having trouble with the same code today.

@mikeburg it appears that `php artisan migrate`, it's not getting the config from the `RANGER_` variables, so it's trying to connect to mysql on loopback instead of the host in `RANGER_DB_HOST_NAME`.

**Comment by wsanchez** [comment]
Oh I bet I need to do some config cache hooey like I do in the app container.

**Comment by wsanchez** [comment]
OK I think i see the issue.

**Comment by wsanchez** [comment]
Serious pilot error.  Never mind me.

**Comment by mikeburg** [comment]
Good news, I tested the client this morning with current API staging server and  everything looks good. This includes the new tables created through the migration process. Login would fail if the migration was not successful. The authentication API records the login event via the new action_logs table.

**Pull request merged**
